In [10]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
from splinter import Browser
import time 
from pprint import pprint

In [11]:
wiki = 'https://en.wikipedia.org/wiki/Economy_of_Venezuela'

In [12]:
all_tables = {}

In [30]:
tables = pd.read_html(wiki)
tables[0]

,0,1
0,Plaza Venezuela in Caracas,NaN
1,Currency,Bolívar soberano (VES)
2,Fixed exchange rates,"DICOM: Bs. 66,937.50=US$1[1]"
3,Fiscal year,Calendar
4,Trade organizations,"WTO, OPEC, Unasur, MERCOSUR, ALBA"
5,Statistics,NaN
6,GDP,"$320.1 billion (2018, PPP) $96.3 billion (2018..."
7,GDP rank,47th (nominal) / 47th (PPP)
8,GDP growth,"-6.0% (2015), -16.5% (2016), -14.5% (2017e), -..."
9,GDP per capita,"$10,968 (2018, PPP) $3,300 (2018, nominal)[3]"
10,GDP by sector,Agriculture: 4.4%Industry: 38.2%Services: 57.4...
11,Inflation (CPI),"65,320% (Hanke's methodology; annual; August 2..."
12,Population below poverty line,19.7% (2015 est.)[2] 87.0% (2017 est.)[7]
13,Labor force,14.21 million (2017 est.)[2]
14,Labor force by occupation,"Communal, social and personal services: 31.4%C..."
15,Unemployment,34.3% (2018)[3]
16,Main industries,"Petroleum, construction materials, food proces..."
17,Ease-of-doing-business rank,188th (2019)[9]
18,External,NaN
19,Exports,$32.08 billion (2017)[10]
20,Export goods,"Petroleum, chemicals, agricultural products an..."
21,Main export partners,United States 42% China 23% India 19% Singapor...
22,Imports,$9.1 billion (2017)[11]
23,Import goods,"Food, clothing, cars, technological items, raw..."
24,Main import partners,United States 38% China 18% Mexico 12% Brazil ...
25,Gross external debt,$100.3 billion (31 December 2017 est.)[2]
26,Public finances,NaN
27,Public debt,38.9% of GDP (2017 est.)[2]
28,Budget balance,-46.1% (of GDP) (2017 est.)[2]
29,Revenues,$92.8 billion (2017 est.)[2]
30,Expenses,$189.7 billion (2017 est.)[2]
31,Credit rating,Standard & Poor's:[12]SD (domestic)SD (foreign...
32,Foreign reserves,$8.500 billion (June 2018)[15] $9.661 billion ...
33,Main data source: CIA World Fact Book All valu...,NaN

In [14]:
len(tables)

28

In [23]:
for i in range (0, 27):
    table = tables[i]
    all_tables[f'tables_{i}']=table

In [39]:
# pprint (all_tables)
for t in all_tables:
     pprint(all_tables[t])

                                                   0  \
0                        vteWorld Trade Organization
1                                             System
2                                             Issues
3                                         Agreements
4                             MinisterialConferences
5                                             People
6                                            Members
7                                     European Union
8  Special administrative regions of the People's...
9                                     European Union

                                                   1               2  \
0                                                NaN             NaN
1  Accession and membership Appellate Body Disput...             NaN
2  Criticism Doha Development Round Singapore iss...             NaN
3  General Agreement on Tariffs and Trade Agricul...             NaN
4  1st (1996) 2nd (1998) 3rd (1999) 4th (2001) 5t...             NaN
5  Roberto Azevêdo (Director-General) Pascal Lamy...             NaN
6  Afghanistan Albania Algeria Angola Antigua and...  European Union
7  Austria Belgium Bulgaria Croatia Cyprus Czech ...             NaN
8                                                NaN             NaN
9  Austria Belgium Bulgaria Croatia Cyprus Czech ...             NaN

                                                   3
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6  Austria Belgium Bulgaria Croatia Cyprus Czech ...
7                                                NaN
8                                                NaN
9                                                NaN
                                                    0  \
0                          Plaza Venezuela in Caracas
1                                            Currency
2                                Fixed exchange rates
3                                         Fiscal year
4                                 Trade organizations
5                                          Statistics
6                                                 GDP
7                                            GDP rank
8                                          GDP growth
9                                      GDP per capita
10                                      GDP by sector
11                                    Inflation (CPI)
12                      Population below poverty line
13                                        Labor force
14                          Labor force by occupation
15                                       Unemployment
16                                    Main industries
17                        Ease-of-doing-business rank
18                                           External
19                                            Exports
20                                       Export goods
21                               Main export partners
22                                            Imports
23                                       Import goods
24                               Main import partners
25                                Gross external debt
26                                    Public finances
27                                        Public debt
28                                     Budget balance
29                                           Revenues
30                                           Expenses
31                                      Credit rating
32                                   Foreign reserves
33  Main data source: CIA World Fact Book All valu...

                                                    1
0                                                 NaN
1                              Bolívar soberano (VES)
2                        DICOM: Bs. 66,937.50=US$1[1]
3                                            Calendar
4                   WTO, OPEC, Unasur, MERCOSUR, ALBA
5                                                 NaN
6   $320.1 billion (2018, PPP) $96.3 billion (2018...
7                         47th (nominal) / 47th (PPP)
8   -6.0% (2015), -16.5% (2016), -14.5% (2017e), -...
9       $10,968 (2018, PPP) $3,300 (2018, nominal)[3]
10  Agriculture: 4.4%Industry: 38.2%Services: 57.4...
11  65,320% (Hanke's methodology; annual; August 2...
12          19.7% (2015 est.)[2] 87.0% (2017 est.)[7]
13                       14.21 million (2017 est.)[2]
14  Communal, social and personal services: 31.4%C...
15                                    34.3% (2018)[3]
16  Petroleum, construction materials, food proces...
17                                    188th (2019)[9]
18                                                NaN
19                          $32.08 billion (2017)[10]
20  Petroleum, chemicals, agricultural products an...
21  United States 42% China 23% India 19% Singapor...
22                            $9.1 billion (2017)[11]
23  Food, clothing, cars, technological items, raw...
24  United States 38% China 18% Mexico 12% Brazil ...
25          $100.3 billion (31 December 2017 est.)[2]
26                                                NaN
27                        38.9% of GDP (2017 est.)[2]
28                     -46.1% (of GDP) (2017 est.)[2]
29                       $92.8 billion (2017 est.)[2]
30                      $189.7 billion (2017 est.)[2]
31  Standard & Poor's:[12]SD (domestic)SD (foreign...
32  $8.500 billion (June 2018)[15] $9.661 billion ...
33                                                NaN
    0                                                  1
0 NaN  This section needs expansion. You can help by ...
                                                   0   \
0   Top Trading Partners for Venezuela for 2017 [123]
1   Imports into Venezuela 2017 Ranking Country Va...
2                         Imports into Venezuela 2017
3                                             Ranking
4                                                 NaN
5                                                   1
6                                                   2
7                                                   3
8                                                   4
9                                                   5
10                                                  6
11                                                  7
12                                                  8
13                                                  9
14                                                 10
15                    Exports from Venezuela for 2017
16                                            Ranking
17                                                NaN
18                                                  1
19                                                  2
20                                                  3
21                                                  4
22                                                  5
23                                                  6
24                                                  7
25                                                  8
26                                                  9
27                                                 10
28                        Imports into Venezuela 2017
29                                            Ranking
30                                                NaN
31                                                  1
32                                                  2
33                                                  3
34                                                  4
35                                                  5
36                                                  6
37                                                  7
38                                                  8
39                                                  9
40                                                 10
41                    Exports from Venezuela for 2017
42                                            Ranking
43                                                NaN
44                                                  1
45                                                  2
46                                                  3
47                                                  4
48                                                  5
49                                                  6
50                                                  7
51                                                  8
52                                                  9
53                                                 10

                             1            2        3            4    5   6   \
0                           NaN          NaN      NaN          NaN  NaN NaN
1   Imports into Venezuela 2017      Ranking  Country  Value (USD)    % NaN
2                           NaN          NaN      NaN          NaN  NaN NaN
3                       Country  Value (USD)        %          NaN  NaN NaN
4                         World        $9.1B   100.0%          NaN  NaN NaN
5                 United States       $3.45B      38%          NaN  NaN NaN
6                         China       $1.65B      18%          NaN  NaN NaN
7                        Mexico       $1.08B      12%          NaN  NaN NaN
8                        Brazil        $469M     5.2%          NaN  NaN NaN
9                      Colombia        $318M     3.5%          NaN  NaN NaN
10                    Argentina        $245M     2.7%          NaN  NaN NaN
11                      Germany        $191M     2.1%          NaN  NaN NaN
12                        Italy        $166M     1.8%          NaN  NaN NaN
13                        Spain        $117M     1.3%          NaN  NaN NaN
14               United Kingdom         $86M    0.95%          NaN  NaN NaN
15                          NaN          NaN      NaN          NaN  NaN NaN
16                      Country  Value (USD)        %          NaN  NaN NaN
17                        World       $27.8B   100.0%          NaN  NaN NaN
18                United States       $11.6B      42%          NaN  NaN NaN
19                        China        $6.4B      23%          NaN  NaN NaN
20                        India       $5.25B      19%          NaN  NaN NaN
21                    Singapore       $1.25B     4,5%          NaN  NaN NaN
22                        Spain        $390M     1,4%          NaN  NaN NaN
23                       Brazil        $363M     1.3%          NaN  NaN NaN
24                       Sweden        $341M     1.2%          NaN  NaN NaN
25                     Malaysia        $316M     1.1%          NaN  NaN NaN
26                      Germany        $259M    0.93%          NaN  NaN NaN
27                     Colombia        $210M    0.75%          NaN  NaN NaN
28                          NaN          NaN      NaN          NaN  NaN NaN
29                      Country  Value (USD)        %          NaN  NaN NaN
30                        World        $9.1B   100.0%          NaN  NaN NaN
31                United States       $3.45B      38%          NaN  NaN NaN
32                        China       $1.65B      18%          NaN  NaN NaN
33                       Mexico       $1.08B      12%          NaN  NaN NaN
34                       Brazil        $469M     5.2%          NaN  NaN NaN
35                     Colombia        $318M     3.5%          NaN  NaN NaN
36                    Argentina        $245M     2.7%          NaN  NaN NaN
37                      Germany        $191M     2.1%          NaN  NaN NaN
38                        Italy        $166M     1.8%          NaN  NaN NaN
39                        Spain        $117M     1.3%          NaN  NaN NaN
40               United Kingdom         $86M    0.95%          NaN  NaN NaN
41                          NaN          NaN      NaN          NaN  NaN NaN
42                      Country  Value (USD)        %          NaN  NaN NaN
43                        World       $27.8B   100.0%          NaN  NaN NaN
44                United States       $11.6B      42%          NaN  NaN NaN
45                        China        $6.4B      23%          NaN  NaN NaN
46                        India       $5.25B      19%          NaN  NaN NaN
47                    Singapore       $1.25B     4,5%          NaN  NaN NaN
48                        Spain        $390M     1,4%          NaN  NaN NaN
49                       Brazil        $363M     1.3%          NaN  NaN NaN
50                       Sweden        $341M     1.2%          NaN  NaN NaN
51                     Malaysia        $316M     1.1%          NaN  NaN NaN
52                      Germany        $259M    0.93%          NaN  NaN NaN
53                     Colombia        $210M    0.75%          NaN  NaN NaN

       7      8       9   ...       90    91   92       93     94     95  \
0     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
1   World  $9.1B  100.0%  ...    $316M  1.1%  9.0  Germany  $259M  0.93%
2     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
3     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
4     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
5     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
6     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
7     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
8     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
9     NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
10    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
11    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
12    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
13    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
14    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
15    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
16    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
17    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
18    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
19    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
20    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
21    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
22    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
23    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
24    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
25    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
26    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
27    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
28    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
29    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
30    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
31    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
32    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
33    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
34    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
35    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
36    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
37    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
38    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
39    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
40    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
41    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
42    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
43    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
44    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
45    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
46    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
47    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
48    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
49    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
50    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
51    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
52    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN
53    NaN    NaN     NaN  ...      NaN   NaN  NaN      NaN    NaN    NaN

      96        97     98     99
0    NaN       NaN    NaN    NaN
1   10.0  Colombia  $210M  0.75%
2    NaN       NaN    NaN    NaN
3    NaN       NaN    NaN    NaN
4    NaN       NaN    NaN    NaN
5    NaN       NaN    NaN    NaN
6    NaN       NaN    NaN    NaN
7    NaN       NaN    NaN    NaN
8    NaN       NaN    NaN    NaN
9    NaN       NaN    NaN    NaN
10   NaN       NaN    NaN    NaN
11   NaN       NaN    NaN    NaN
12   NaN       NaN    NaN    NaN
13   NaN       NaN    NaN    NaN
14   NaN       NaN    NaN    NaN
15   NaN       NaN    NaN    NaN
16   NaN       NaN    NaN    NaN
17   NaN       NaN    NaN    NaN
18   NaN       NaN    NaN    NaN
19   NaN       NaN    NaN    NaN
20   NaN       NaN    NaN    NaN
21   NaN       NaN    NaN    NaN
22   NaN       NaN    NaN    NaN
23   NaN       NaN    NaN    NaN
24   NaN       NaN    NaN    NaN
25   NaN       NaN    NaN    NaN
26   NaN       NaN    NaN    NaN
27   NaN       NaN    NaN    NaN
28   NaN       NaN    NaN    NaN
29   NaN       NaN    NaN    NaN
30   NaN       NaN    NaN    NaN
31   NaN       NaN    NaN    NaN
32   NaN       NaN    NaN    NaN
33   NaN       NaN    NaN    NaN
34   NaN       NaN    NaN    NaN
35   NaN       NaN    NaN    NaN
36   NaN       NaN    NaN    NaN
37   NaN       NaN    NaN    NaN
38   NaN       NaN    NaN    NaN
39   NaN       NaN    NaN    NaN
40   NaN       NaN    NaN    NaN
41   NaN       NaN    NaN    NaN
42   NaN       NaN    NaN    NaN
43   NaN       NaN    NaN    NaN
44   NaN       NaN    NaN    NaN
45   NaN       NaN    NaN    NaN
46   NaN       NaN    NaN    NaN
47   NaN       NaN    NaN    NaN
48   NaN       NaN    NaN    NaN
49   NaN       NaN    NaN    NaN
50   NaN       NaN    NaN    NaN
51   NaN       NaN    NaN    NaN
52   NaN       NaN    NaN    NaN
53   NaN       NaN    NaN    NaN

[54 rows x 100 columns]
                              0               1            2       3
0   Imports into Venezuela 2017             NaN          NaN     NaN
1                       Ranking         Country  Value (USD)       %
2                           NaN           World        $9.1B  100.0%
3                             1   United States       $3.45B     38%
4                             2           China       $1.65B     18%
5                             3          Mexico       $1.08B     12%
6                             4          Brazil        $469M    5.2%
7                             5        Colombia        $318M    3.5%
8                             6       Argentina        $245M    2.7%
9                             7         Germany        $191M    2.1%
10                            8           Italy        $166M    1.8%
11                            9           Spain        $117M    1.3%
12                           10  United Kingdom         $86M   0.95%
                                  0              1            2       3
0   Exports from Venezuela for 2017            NaN          NaN     NaN

In [50]:
GDP_data = tables[6]
GDP_data

,0,1,2,3,4,5,6
0,Year,GDP(in Bil. US$ PPP),GDP per capita(in US$ PPP),GDP growth(real),Inflation rate(in Percent),Unemployment (in Percent),Government debt(in % of GDP))
1,1980,117.2,7838,−4.9 %,21.4 %,NaN,NaN
2,1981,126.5,8208,−1.3 %,16.2 %,NaN,NaN
3,1982,137.9,8690,2.6 %,9.6 %,NaN,NaN
4,1983,129.2,7919,−9.9 %,6.2 %,NaN,NaN
5,1984,140.8,8392,5.2 %,12.3 %,NaN,NaN
6,1985,146.5,8499,0.9 %,11.4 %,NaN,NaN
7,1986,158.6,9088,6.1 %,11.5 %,NaN,NaN
8,1987,170.4,9528,4.8 %,28.1 %,NaN,NaN
9,1988,187.9,10247,6.5 %,29.5 %,NaN,NaN
10,1989,168.0,8945,−13.9 %,84.5 %,NaN,NaN
11,1990,185.5,9557,6.5 %,40.7 %,NaN,NaN
12,1991,210.3,10581,9.8 %,34.2 %,NaN,NaN
13,1992,228.2,11214,6.1 %,31.4 %,NaN,NaN
14,1993,234.2,11253,0.3 %,38.1 %,NaN,NaN
15,1994,233.6,10976,−2.3 %,60.8 %,NaN,NaN
16,1995,247.9,11397,4.0 %,59.9 %,NaN,NaN
17,1996,251.9,11338,−0.2 %,99.9 %,NaN,NaN
18,1997,272.6,12020,6.4 %,50.0 %,NaN,NaN
19,1998,276.3,11946,0.3 %,35.8 %,NaN,31.4 %
20,1999,263.8,11182,−6.0 %,23.6 %,14.5 %,31.2 %
21,2000,279.8,11468,3.7 %,16.2 %,14.0 %,28.2 %
22,2001,295.8,11928,3.4 %,12.5 %,13.4 %,31.7 %
23,2002,273.8,10859,−8.9 %,22.4 %,16.0 %,55.0 %
24,2003,257.6,10053,−7.8 %,31.1 %,18.2 %,55.8 %
25,2004,313.1,12026,18.3 %,21.7 %,"15,1 %",42.2 %
26,2005,356.5,13480,10.3 %,16.0 %,12.2 %,35.6 %
27,2006,403.7,15031,9.9 %,13.7 %,10.0 %,25.7 %
28,2007,450.7,16527,8.8 %,18.7 %,8.5 %,26.4 %
29,2008,483.8,17474,5.3 %,31.4 %,7.4 %,20.3 %
30,2009,471.9,16790,−3.2 %,26.0 %,7.9 %,27.6 %
31,2010,470.6,16776,−1.5 %,28.2 %,8.5 %,36.5 %
32,2011,500.3,17286,4.2 %,26.1 %,8.2 %,50.6 %
33,2012,538.2,18327,5.6 %,21.1 %,7.8 %,58.1 %
34,2013,554.2,18607,1.3 %,43.5 %,7.5 %,72.3 %
35,2014,542.2,17951,−3.9 %,57.3 %,6.7 %,63.5 %
36,2015,514.0,16786,−6.2 %,111.8 %,7.4 %,31.9 %
37,2016,434.9,14016,−16.5 %,254.4 %,20.6 %,31.3 %
38,2017,380.7,12113,−14.0 %,"1,087.5 %",27.1 %,34.9 %
39,2018 (est.),331.0,10399,−15.0 %,"13,864.6 %",33.4 %,162.0 %

In [51]:
Economic_data = tables[0]
Economic_data

,0,1
0,Plaza Venezuela in Caracas,NaN
1,Currency,Bolívar soberano (VES)
2,Fixed exchange rates,"DICOM: Bs. 66,937.50=US$1[1]"
3,Fiscal year,Calendar
4,Trade organizations,"WTO, OPEC, Unasur, MERCOSUR, ALBA"
5,Statistics,NaN
6,GDP,"$320.1 billion (2018, PPP) $96.3 billion (2018..."
7,GDP rank,47th (nominal) / 47th (PPP)
8,GDP growth,"-6.0% (2015), -16.5% (2016), -14.5% (2017e), -..."
9,GDP per capita,"$10,968 (2018, PPP) $3,300 (2018, nominal)[3]"
10,GDP by sector,Agriculture: 4.4%Industry: 38.2%Services: 57.4...
11,Inflation (CPI),"65,320% (Hanke's methodology; annual; August 2..."
12,Population below poverty line,19.7% (2015 est.)[2] 87.0% (2017 est.)[7]
13,Labor force,14.21 million (2017 est.)[2]
14,Labor force by occupation,"Communal, social and personal services: 31.4%C..."
15,Unemployment,34.3% (2018)[3]
16,Main industries,"Petroleum, construction materials, food proces..."
17,Ease-of-doing-business rank,188th (2019)[9]
18,External,NaN
19,Exports,$32.08 billion (2017)[10]
20,Export goods,"Petroleum, chemicals, agricultural products an..."
21,Main export partners,United States 42% China 23% India 19% Singapor...
22,Imports,$9.1 billion (2017)[11]
23,Import goods,"Food, clothing, cars, technological items, raw..."
24,Main import partners,United States 38% China 18% Mexico 12% Brazil ...
25,Gross external debt,$100.3 billion (31 December 2017 est.)[2]
26,Public finances,NaN
27,Public debt,38.9% of GDP (2017 est.)[2]
28,Budget balance,-46.1% (of GDP) (2017 est.)[2]
29,Revenues,$92.8 billion (2017 est.)[2]
30,Expenses,$189.7 billion (2017 est.)[2]
31,Credit rating,Standard & Poor's:[12]SD (domestic)SD (foreign...
32,Foreign reserves,$8.500 billion (June 2018)[15] $9.661 billion ...
33,Main data source: CIA World Fact Book All valu...,NaN

In [53]:
Personal_income = tables[8]
Personal_income

,0,1,2,3,4,5,6,7
0,Year,Share of personal income (%) received by:,GINI index,NaN,NaN,NaN,NaN,NaN
1,Poorest fifth,2nd fifth,3rd fifth,4th fifth,Wealthiest fifth,Wealthiest 10%,NaN,NaN
2,1987,4.7,9.2,14.0,21.5,50.6,34.2,~43.42
3,1995,4.3,8.8,13.8,21.3,51.8,35.6,46.8
4,1996,3.7,8.4,13.6,21.2,53.1,37.0,48.8
5,2000,4.7,9.4,14.5,22.1,45.4,29.9,42.0
6,2004,3.5,—,12.9,—,54.8,—,45.59
7,2007,5.1,—,14.2,—,47.7,—,42.37
8,2010,5.7,—,14.9,—,44.8,—,38.98
9,2011,5.7,—,15.9,—,44.8,—,39.02
10,2013,—,—,—,—,—,—,44.8
11,2015,—,—,—,—,—,—,46.9
12,Note that personal (per capita) income distrib...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
Percent_below_pov_line = tables[9]
Percent_below_pov_line

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Year,1989,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,...,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014,2015,2016,2017
1,Households,–,48.1,43.9,42.0,40.4,39.0,48.6,55.1,47.0,...,27.5,26.7,26.9,26.5,21.1,27.3,48.4,73.0,81.8,87.0
2,People,31.3,54.5,50.4,48.7,46.3,45.4,55.4,62.1,53.9,...,32.6,31.8,32.5,31.6,25.4,32.1,–,–,–,–
3,"Sources World Bank, 1997 World Development Ind...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN